development:
  adapter: mysql
  encoding: utf8
  database: man_evolution
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: man_evolution
  username: root
  password:
